version: "3.5"

x-environment:
  &default-back-environment
  POSTGRES_DB: ${DOCKER_DB_NAME}
  POSTGRES_USER: ${DOCKER_DB_USER}
  POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
  POSTGRES_HOST: taiga-db
  TAIGA_SECRET_KEY: ${SECRET_KEY}
  # these rabbitmq settings should be the same as
  # in taiga-rabbitmq and taiga-events services
  RABBITMQ_USER: ${DOCKER_RABBITMQ_USER}
  RABBITMQ_PASS: ${DOCKER_RABBITMQ_PASSWORD}
  CELERY_ENABLED: "True"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-manage:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
    volumes: *default-back-volumes
    networks:
      - taiga
